Prevent Fuzzilli from generating async arrow functions during mutation
Summary:
Hermes currently does not support async arrow functions, so let's prevent `AsyncArrowFunctionGenerator` from being selected by the `CodeGenMutator`

```test.js

async function asyncFunction() {
  console.log('test');
}

(async () => {
    console.log(await asyncFunction());
})();
```

```./hermes test.js
test.js:5:2: error: async functions are unsupported
(async () => {
 ^~~~~~~~~~~~~
Emitted 1 errors. exiting.
```

Differential Revision: D39601546

fbshipit-source-id: 120ae9ebdc1a9552ae2a034592b8af302dc07716