Fix compile error due to `-Wdefaulted-function-deleted`
Summary:
Error was

```
In file included from /tmp/tmp.BZRqJWpv1Q/hermes/lib/VM/CodeBlock.cpp:9:
In file included from /tmp/tmp.BZRqJWpv1Q/hermes/include/hermes/VM/CodeBlock.h:10:
In file included from /tmp/tmp.BZRqJWpv1Q/hermes/include/hermes/BCGen/HBC/BytecodeDataProvider.h:11
:
/tmp/tmp.BZRqJWpv1Q/hermes/include/hermes/BCGen/HBC/DebugInfo.h:293:3: error: explicitly defaulted copy constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
  DebugInfoGenerator(const DebugInfoGenerator &) = default;
  ^
/tmp/tmp.BZRqJWpv1Q/hermes/include/hermes/BCGen/HBC/DebugInfo.h:266:28: note: copy constructor of 'DebugInfoGenerator' is implicitly deleted because field 'filenameStrings_' has a deleted copy constructor
  ConsecutiveStringStorage filenameStrings_;
                           ^
/tmp/tmp.BZRqJWpv1Q/hermes/include/hermes/BCGen/HBC/ConsecutiveStringStorage.h:42:3: note: 'ConsecutiveStringStorage' has been explicitly marked deleted here
  ConsecutiveStringStorage(const ConsecutiveStringStorage &) = delete;
  ^
In file included from /tmp/tmp.AelfMCcQqO/hermes/lib/VM/CodeBlock.cpp:9:
In file included from /tmp/tmp.AelfMCcQqO/hermes/include/hermes/VM/CodeBlock.h:10:
In file included from /tmp/tmp.AelfMCcQqO/hermes/include/hermes/BCGen/HBC/BytecodeDataProvider.h:11:
/tmp/tmp.AelfMCcQqO/hermes/include/hermes/BCGen/HBC/DebugInfo.h:294:23: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
  DebugInfoGenerator &operator=(const DebugInfoGenerator &) = default;
                      ^
/tmp/tmp.AelfMCcQqO/hermes/include/hermes/BCGen/HBC/DebugInfo.h:266:28: note: copy assignment operator of 'DebugInfoGenerator' is implicitly deleted because field 'filenameStrings_' has a deleted copy assignment operator
  ConsecutiveStringStorage filenameStrings_;
                           ^
/tmp/tmp.AelfMCcQqO/hermes/include/hermes/BCGen/HBC/ConsecutiveStringStorage.h:39:29: note: 'operator=' has been explicitly marked deleted here
  ConsecutiveStringStorage &operator=(const ConsecutiveStringStorage &_) =
                            ^
In file included from /tmp/tmp.X2tViTekwh/hermes/lib/AST/ASTBuilder.cpp:7:
In file included from /tmp/tmp.X2tViTekwh/hermes/include/hermes/AST/ASTBuilder.h:12:
/tmp/tmp.X2tViTekwh/hermes/include/hermes/Parser/JSONParser.h:342:15: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
    iterator &operator=(const iterator &) = default;
              ^
/tmp/tmp.X2tViTekwh/hermes/include/hermes/Parser/JSONParser.h:333:23: note: copy assignment operator of 'iterator' is implicitly deleted because field 'obj_' is of const-qualified type 'hermes::parser::JSONObject *const'
    JSONObject *const obj_;
                      ^
```

Reviewed By: mhorowitz

Differential Revision: D15698654

fbshipit-source-id: cdc87f541647e6c79ebc7c9381ed98d0a21c8602