Fix compilation of hermes_comments tests
Summary:
Broken since {D58156907}.

```lang=log,counterexample
error[E0308]: mismatched types
  --> xplat/hermes/unsupported/hermes/crates/hermes_comments/tests/test.rs:46:23
   |
46 |             .sort_by(|(comment1, _, _), (comment2, _, _)| comment1.trim().cmp(comment2.trim()));
   |                       ^^^^^^^^^^^^^^^^
   |                       |
   |                       expected a tuple with 4 elements, found one with 3 elements
   |                       expected due to this
   |
   = note: expected tuple `(&str, SourceRange, Node<'_>, SourceRange)`
              found tuple `(_, _, _)`

error[E0308]: mismatched types
  --> xplat/hermes/unsupported/hermes/crates/hermes_comments/tests/test.rs:46:41
   |
46 |             .sort_by(|(comment1, _, _), (comment2, _, _)| comment1.trim().cmp(comment2.trim()));
   |                                         ^^^^^^^^^^^^^^^^
   |                                         |
   |                                         expected a tuple with 4 elements, found one with 3 elements
   |                                         expected due to this
   |
   = note: expected tuple `(&str, SourceRange, Node<'_>, SourceRange)`
              found tuple `(_, _, _)`
```

Reviewed By: diliop

Differential Revision: D82673558

fbshipit-source-id: 551675621bdf861314d50317ee4f65594f100e6b