Remove use of makeArrayRef in BigIntSupportTest
Summary:
GCC complains:
```
hermes/unittests/Support/BigIntSupportTest.cpp:470:17: error: call of overloaded ‘makeArrayRef<uint8_t>(<brace-enclosed initializer list>)’ is ambiguous
            0x80})),
```

We can just call the constructor of `ArrayRef` which has an overload
for initialiser lists.

Reviewed By: jpporto

Differential Revision: D38300739

fbshipit-source-id: 286a856e6b375fda7f11cf69633413566732c25d