Add missing cstdint includes (#1040)
Summary:
I added the missing <cstdint> includes to fix build errors when using uint*_t with clang 16. I also added .cache to gitignore so I don't acidentally commit the clangd LSP cache directory.

The errors that this PR fixes look like this:
```
          ^
/home/theo/dev/hermes/public/hermes/Public/../../hermes/Public/DebuggerTypes.h:40:11: error: unknown type name 'uint64_t'
constexpr uint64_t kInvalidBreakpoint = 0;
```

Pull Request resolved: https://github.com/facebook/hermes/pull/1040

Reviewed By: avp

Differential Revision: D47271899

Pulled By: neildhar

fbshipit-source-id: 4f3bdfc1c90583fdfcbbe10c3c9cc84e7f7bb690