Fix intl build (#1030)
Summary:
Pull Request resolved: https://github.com/facebook/hermes/pull/1030

Build is failing due to:
```
stderr: xplat/hermes/lib/VM/JSLib/Intl.cpp:280:55: error: missing field 'flags' initializer [-Werror,-Wmissing-field-initializers]
    {u"dayPeriod", platform_intl::Option::Kind::String},
```

This line is brought in via GitHub Pull Request: D45185307

Reviewed By: neildhar

Differential Revision: D46750063

fbshipit-source-id: e5b7fa65a0ec5db7c5e45f92fcf828a5e55c1060