Prevent Fuzzilli from generating classes during mutation
Summary:
Hermes currently does not support [class definitions](https://github.com/facebook/hermes/blob/main/doc/Features.md?plain=1#L44), so let's prevent `ClassGenerator` from being selected by the `CodeGenMutator`

```test.js
class Test {

}
```

```./hermes test.js
error: invalid statement encountered.
class Test {
^~~~~~~~~~~~
Emitted 1 errors. exiting.
```

Differential Revision: D39083831

fbshipit-source-id: cfc13dd3c1daf9b95d3f8ec8c64431c0e7662caa