Fix unused variable error
Summary:
Was seeing the following error:
```
stderr:
xplat/static_h/lib/IRGen/ESTreeIRGen-func.cpp:1054:8: error: unused variable '[it, inserted]' [-Werror,-Wunused-variable]
 1054 |   auto [it, inserted] = compiledEntities_.try_emplace(key, F);
      |        ^
1 error generated.
```

Reviewed By: neildhar

Differential Revision: D58211230

fbshipit-source-id: 3879905557bcf49464d8628aa344209211277669