Fix ambiguous operator overload in libc++19
Summary:
See error, caused by D62161925, this fix is similar to D62771872:

```
xplat/shermes/stable/lib/BCGen/SH/LineDirectiveEmitter.cpp:71:9: error: use of overloaded operator '=' is ambiguous (with operand types 'LineDirectiveInfo' (aka 'pair<unsigned int, llvh::StringRef>') and 'void')
[CONTEXT]    71 |   info_ = {};
[CONTEXT]       |   ~~~~~ ^ ~~
```

Differential Revision: D64615094

fbshipit-source-id: 551c308eba42715189ca8fbf6da0bcca45e664e7