JSError: never fail with invalid getter target (#1620)
Summary:
Pull Request resolved: https://github.com/facebook/hermes/pull/1620

JS developers expect this to work and print "undefined":
```js
function MyEror() {
    this.message = "MyError";
}
MyError.prototype = Object.create(Error.prototype);
try {
    throw new MyError();
} catch (e) {
    print(e.stack);
}
```

We give it to them by preventing the getter from throwing errors. In V8
this is implemented differently by attaching the getter to the actual
instance.

Arguably, this makes sense, because property reads shouldn't throw.

Add and update tests.

Reviewed By: avp

Differential Revision: D69757361

fbshipit-source-id: 4c03a908a5423e6b511325e6df629aa22407e335