Add public header search paths to libhermes target.
    Resolves users hitting the following error:

    fatal error: hermes/Public/RuntimeConfig.h: No such file or directory
    at #include <hermes/Public/RuntimeConfig.h>

    This means users simply need to call target_link_libraries(target libHermes).