Add HermesExecutor to first-party
Summary:
This adds a modified HermesExecutor to first-party, along with some patches to
allow building it through an otherwise untouched react-native checkout. It's
currently enough to cause a RN build to fail due to missing Hermes public API:

```
[armeabi-v7a] SharedLibrary  : libhermes-executor.so
/Users/willholen/newoss/AwesomeProject/node_modules/react-native/ReactAndroid/src/main/jni/../../../../../../../hermes/first-party/hermes-executor/src/main/java/com/facebook/hermes/reactexecutor/HermesExecutorFactory.cpp:27: error: undefined reference to 'facebook::hermes::makeHermesRuntime(hermes::vm::RuntimeConfig const&, bool)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Reviewed By: mhorowitz

Differential Revision: D13934549

fbshipit-source-id: 5d73d93e8ef31bc206b9c40f7c884c8a57be7f67