Catch JSError by reference as required by GCC8
Summary:
Fixes `-Werror=catch-value=`:

    error: catching polymorphic type ‘class facebook::jsi::JSError’ by value

Reviewed By: tmikov

Differential Revision: D13822201

fbshipit-source-id: ada8a2ea325b044a280502a8ecb0eb10558392ad