Link with libpthread for asan builds
Summary:
`libasan` provides its own implementaiton of `pthread_create` which
can lead to CMake thinking that there is no need to explicitly link
against `libpthread`. Clang gets around this by always adding
`-lpthread` when building with `-fsanitize=address` but GCC does not.
This leads to errors like:
```
/opt/rh/gcc-toolset-9/root/usr/bin/ld: external/llvh/lib/Support/libLLVHSupport.a(Process.cpp.o): undefined reference to symbol 'pthread_sigmask@GLIBC_2.2.5'
/opt/rh/gcc-toolset-9/root/usr/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

This change adds the `-lpthread` flag for all ASAN builds.

This seems to be a known issue:
https://wiki.gentoo.org/wiki/AddressSanitizer/Problems#pthread_linking_issues

And is fixed after CMake 3.15:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/3040

Reviewed By: dulinriley

Differential Revision: D22190290

fbshipit-source-id: 1421dd5007b1494621181b9209619f821ac0634f