Prevent Fuzzilli from generating async generators during mutation
Summary:
Hermes currently does not support [async generator functions](https://github.com/facebook/hermes/blob/b7d275dbc5c4ad6775ef757efcdd964f88382f8b/doc/Features.md?plain=1#L37), so let's prevent `AsyncGeneratorFunctionGenerator` from being selected by the `CodeGenMutator`

```test.js

async function* foo() {
  yield await Promise.resolve('bar');
}
```

```./hermes test.js
test.js:1:1: error: async generators are unsupported
async function* foo() {
^~~~~~~~~~~~~~~~~~~~~~~
Emitted 1 errors. exiting.
```

Differential Revision: D39601483

fbshipit-source-id: 23602a1bab22312bab83dc6be2defd4e588bb31d