fix lexing for flow typeof annotations
Summary:
noticed a bug introduced by D44099358: types like `A<B<typeof a>>` or `A<B<typeof a.a>>` would fail.

example:
```
error: '>' expected at end of type parameters
type T = A<B<typeof a>>;
            ~~~~~~~~~^
```

upon debugging, i noticed the following token was being lexed as `>>` instead of `>`, suggesting that we were using an incorrect GrammerContext. updates calls to `advance` here with `JSLexer::GrammarContext::Type`

Reviewed By: avp

Differential Revision: D44917959

fbshipit-source-id: f2041f8dbf695a4dace7e75d094ff9b74f0ff03a