Fix intl build
Summary:
Build is failing due to:
```
stderr: xplat/hermes/lib/VM/JSLib/Intl.cpp:280:55: error: missing field 'flags' initializer [-Werror,-Wmissing-field-initializers]
    {u"dayPeriod", platform_intl::Option::Kind::String},
```

This line is brought in via GitHub Pull Request: D45185307

Reviewed By: neildhar

Differential Revision: D46750063

fbshipit-source-id: d15323f66005bbf876a4e049cbb987762d3ad09b