Fix: Fix fuzzilli compilation error
If you are using the recent hermes source code, you need to comment out the following code in order to compile successfully.
external/llvh/cmake/config-ix.cmake:323
```

# Define LLVM_HAS_ATOMICS if gcc or MSVC atomic builtins are supported.
# include(CheckAtomic)
```